<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-23FIJ9EA" ignored="0" name="Simple Test" tests="7" failures="1" timestamp="2020-05-31T17:41:20 CEST" time="265.629" errors="0">
  <testcase name="test1_StartWebDriver" time="5.98" classname="com.example.Main"/>
  <testcase name="test2_Login" time="40.291" classname="com.example.Main"/>
  <testcase name="test3_AddNewProject" time="87.188" classname="com.example.Main">
    <failure type="java.lang.AssertionError" message="expected [2] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [3]
at com.example.Main.test3_AddNewProject(Main.java:96)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test3_AddNewProject -->
  <testcase name="test4_SelectProject" time="28.832" classname="com.example.Main"/>
  <testcase name="test5_AddDataToSelectedProject" time="48.461" classname="com.example.Main"/>
  <testcase name="test6_EditDataFromSelectedProject" time="25.485" classname="com.example.Main"/>
  <testcase name="test7_DeleteDataFromSelectedProject" time="29.358" classname="com.example.Main"/>
</testsuite> <!-- Simple Test -->
